import Head from 'next/head'
import { SCREEN_ROUTES } from '../config/paths';
import ItemsList from '../src/components/items/ItemsList';
import MainLayout from '../src/layouts/MainLayout'
import itemService from '../src/services/item.service';

export default function Home({data}) {
  return (
    <MainLayout title="Mercado Libre" categories={data.map(d => d.category)}>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ItemsList items={data} />
    </MainLayout>
  )
}

export const getServerSideProps = async (context) => {
  const data = await itemService.SearchItem('');
  return {
    props: { data }
  }
}