version: "3"
services:
  caching:
    image: redis:latest
    ports:
      - "49153:6379"
  backend:
    build: 
      context: ./zulu_api
      dockerfile: Dockerfile
    ports:
      - "1027:10369"
    depends_on:
      - caching
  
  frontend:
    build: 
      context: ./zulu_web
      dockerfile: Dockerfile
    env_file:
      - ./zulu_web/.env
    ports:
      - "1028:3000"      
    depends_on:
      - backend